In [1]:
import os
import scipy.io as sio
import numpy as np

# Mac
#data_root = '/Volumes/GoogleDrive/My Drive/colab_data/action_datasets'
# Windows
data_root = 'G:\\My Drive\\colab_data\\action_datasets'
dataset = 'hmdb51'  # ucf101

# /Volumes/GoogleDrive/My Drive/colab_data/action_datasets/hmdb51'
dataset_path = os.path.join(data_root, dataset)

# /Volumes/GoogleDrive/My Drive/colab_data/action_datasets/hmdb51/hmdb51_semantics/split_1/att_splits.mat'
split_path = os.path.join(dataset_path, 'hmdb51_semantics/split_1')

mat_i3d = sio.loadmat(dataset_path + '/hmdb51_i3d.mat')
mat_split = sio.loadmat(split_path + '/att_splits.mat')

all_labels = mat_i3d['labels']
all_labels_names = mat_split['allclasses_names']
test_unseen_loc = mat_split['test_unseen_loc']

In [2]:
all_labels = all_labels.squeeze() - 1
test_unseen_loc = test_unseen_loc.squeeze() - 1 

print(all_labels)
print(len(all_labels))
print(test_unseen_loc)
print(len(test_unseen_loc))


[ 0  0  0 ... 50 50 50]
6766
[   0    1    2 ... 6659 6660 6661]
3616


In [3]:
all_labels_names_clean = []
for i in range(len(all_labels_names)):
    all_labels_names_clean.append(all_labels_names[i][0][0])

all_labels_names = np.array(all_labels_names_clean)

# All labels names
print(all_labels_names)

['brush hair' 'cart wheel' 'catch' 'chew' 'clap' 'climb' 'climb stairs'
 'dive' 'draw sword' 'dribble' 'drink' 'eat' 'fall floor' 'fencing'
 'flic flac' 'golf' 'hand stand' 'hit' 'hug' 'jump' 'kick' 'kick ball'
 'kiss' 'laugh' 'pick' 'pour' 'pullup' 'punch' 'push' 'pushup' 'ride bike'
 'ride horse' 'run' 'shake hands' 'shoot ball' 'shoot bow' 'shoot gun'
 'sit' 'situp' 'smile' 'smoke' 'somersault' 'stand' 'swing baseball'
 'sword exercise' 'sword' 'talk' 'throw' 'turn' 'walk' 'wave']


In [4]:
unseen_label = all_labels[test_unseen_loc]

# print(len(np.unique(unseen_label))) # should be 25
# print(len(all_labels_names[unseen_label])) # shplit 1: 3616 testing videos

In [5]:
np.unique(unseen_label)

array([ 0,  2,  5,  8, 10, 11, 12, 15, 16, 17, 18, 20, 21, 22, 27, 28, 29,
       30, 32, 33, 36, 38, 45, 48, 49], dtype=uint8)

In [6]:
unique_unseen_label = np.unique(unseen_label)
unseen_label_name = []
for i in range(len(unique_unseen_label)):
    unseen_label_name.append(all_labels_names[unique_unseen_label[i]])
print(unseen_label_name)
    
    

['brush hair', 'catch', 'climb', 'draw sword', 'drink', 'eat', 'fall floor', 'golf', 'hand stand', 'hit', 'hug', 'kick', 'kick ball', 'kiss', 'punch', 'push', 'pushup', 'ride bike', 'run', 'shake hands', 'shoot gun', 'situp', 'sword', 'turn', 'walk']


In [7]:
import csv
with open('hmdb51_acc_per_class_all.csv', 'a+') as f:
    write = csv.writer(f)
    write.writerow(unseen_label_name)

In [17]:
import csv

# Mac
# results_root = '/Volumes/GoogleDrive/My Drive/colab_data/KG_GCN_GAN/zsl'
# Windows
results_root = 'G:\\My Drive\\colab_data\\KG_GCN_GAN\\zsl'

file = 'exp_zsl_results_hmdb51_action_class_w2v_avg_img_googlenet_me_max_dual.txt'
split =[]
acc_per_class = []
acc_per_class_all_split = []

with open(os.path.join(results_root, dataset, file)) as f:
    lines = [line.rstrip() for line in f]
    # sp1: 10,11,12; sp2: 23,24,25; sp3: 36,37,38
    for i in range(0,3):
        split = lines[10+i*13] + lines[11+i*13] + lines[12+i*13]
        #print(split)
        acc_per_class = split.replace('(', '').replace(')', '').replace('[', '').replace(']', '').replace(' ', '').replace('BestZSLunseenper-classaccuracy:tensor', '').split(',')
        #print(acc_per_class)
        acc_per_class_all_split.append(acc_per_class)
        
        with open('hmdb51_acc_per_class_all.csv', 'a+') as f:
            write = csv.writer(f)
            write.writerow(acc_per_class)
            

In [9]:
split1 = lines[10] + lines[11] + lines[12]
split1

'Best ZSL unseen per-class accuracy: tensor([0.0280, 0.0196, 0.1019, 0.4466, 0.2866, 0.4259, 0.3088, 0.9429, 0.9646,        0.2756, 0.0508, 0.1385, 0.4453, 0.6176, 0.0079, 0.0086, 0.3592, 0.7767,        0.1422, 0.6173, 0.2718, 0.3524, 0.0394, 0.1292, 0.3887])'

In [10]:
acc_per_class_sp1 = split1.replace('(', '').replace(')', '').replace('[', '').replace(']', '').replace(' ', '').replace('BestZSLunseenper-classaccuracy:tensor', '').split(',')

In [11]:
acc_per_class_sp1

['0.0280',
 '0.0196',
 '0.1019',
 '0.4466',
 '0.2866',
 '0.4259',
 '0.3088',
 '0.9429',
 '0.9646',
 '0.2756',
 '0.0508',
 '0.1385',
 '0.4453',
 '0.6176',
 '0.0079',
 '0.0086',
 '0.3592',
 '0.7767',
 '0.1422',
 '0.6173',
 '0.2718',
 '0.3524',
 '0.0394',
 '0.1292',
 '0.3887']

In [12]:
# next 13 lines for next split
split2 = lines[23] + lines[24] + lines[25]
split2

'Best ZSL unseen per-class accuracy: tensor([0.4393, 0.6822, 0.0000, 0.6308, 0.1111, 0.7685, 0.0956, 0.6121, 0.0000,        0.0000, 0.0265, 0.1987, 0.6538, 0.7891, 0.0000, 0.6415, 0.0086, 0.6893,        0.5049, 0.5991, 0.9237, 0.2762, 0.0571, 0.8531, 0.1538])'

In [13]:
acc_per_class_sp2 = split2.replace('(', '').replace(')', '').replace('[', '').replace(']', '').replace(' ', '').replace('BestZSLunseenper-classaccuracy:tensor', '').split(',')

In [16]:
acc_per_class_sp2

['0.4393',
 '0.6822',
 '0.0000',
 '0.6308',
 '0.1111',
 '0.7685',
 '0.0956',
 '0.6121',
 '0.0000',
 '0.0000',
 '0.0265',
 '0.1987',
 '0.6538',
 '0.7891',
 '0.0000',
 '0.6415',
 '0.0086',
 '0.6893',
 '0.5049',
 '0.5991',
 '0.9237',
 '0.2762',
 '0.0571',
 '0.8531',
 '0.1538']